name: repoman

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Setup repoman
      run: |
        python -m pip install --upgrade pip
        pip install lxml pyyaml
        wget -qO - "https://github.com/gentoo/portage/archive/portage-3.0.12.tar.gz" | tar xz
        sudo groupadd -g 250 portage
        sudo useradd -g portage -d /var/tmp/portage -s /bin/false -u 250 portage
        mkdir -p metadata/repoman
        wget -O metadata/repoman/qa_data.yml https://gitweb.gentoo.org/proj/portage.git/plain/repoman/cnf/repository/qa_data.yaml
        wget -O metadata/repoman/repository.yml https://gitweb.gentoo.org/proj/portage.git/plain/repoman/cnf/repository/repository.yaml
        sed -i "s/file.empty/file.empty\n    - file.size/" metadata/repoman/qa_data.yaml
    - name: Setup master gentoo repository
      run: |
        sudo mkdir -p /var/db/repos/gentoo /etc/portage /var/cache/distfiles
        wget -qO - "https://github.com/gentoo-mirror/gentoo/archive/master.tar.gz" | sudo tar xz -C /var/db/repos/gentoo --strip-components=1
        sudo wget "https://www.gentoo.org/dtd/metadata.dtd" -O /var/cache/distfiles/metadata.dtd
        sudo wget "https://gitweb.gentoo.org/proj/portage.git/plain/cnf/repos.conf" -O /etc/portage/repos.conf
        sudo ln -s /var/db/repos/gentoo/profiles/default/linux/amd64/17.0 /etc/portage/make.profile
    - name: Test with repoman
      run: |
        python3 portage-portage-3.0.12/repoman/bin/repoman full -dx
      env:
        REPOMAN_DEFAULT_OPTS:"--experimental-repository-modules=y"
